In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
import fredapi as fa
import requests
import json
import prettytable
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from pandas.tseries.frequencies import to_offset

In [2]:
def data_grabber( ticker):
        #Function designed to take any ticker and grab annual data
        ticker = yf.Ticker(ticker)
        ticker_data = ticker.history(period = "max", interval = "1d")
        
        if not ticker_data.empty:
            return ticker_data
        else:
            print(f"The associated data for {ticker} is empty")
       
        return ticker_data
    
    #Overall Market Metrics

In [3]:
df_AMZN = data_grabber("AMZN")

In [30]:
display(df_AMZN.iloc[-61:-1])

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-11-13 00:00:00-05:00,142.080002,143.229996,140.669998,142.589996,35680600,0.0,0.0
2023-11-14 00:00:00-05:00,145.000000,147.259995,144.679993,145.800003,56674600,0.0,0.0
2023-11-15 00:00:00-05:00,147.059998,147.289993,142.589996,143.199997,63875700,0.0,0.0
2023-11-16 00:00:00-05:00,140.910004,143.320007,139.520004,142.830002,49653500,0.0,0.0
2023-11-17 00:00:00-05:00,142.660004,145.229996,142.539993,145.179993,49636700,0.0,0.0
2023-11-20 00:00:00-05:00,145.130005,146.630005,144.729996,146.130005,41951200,0.0,0.0
2023-11-21 00:00:00-05:00,143.910004,144.050003,141.500000,143.899994,71226000,0.0,0.0
2023-11-22 00:00:00-05:00,144.570007,147.740005,144.570007,146.710007,45669100,0.0,0.0
2023-11-24 00:00:00-05:00,146.699997,147.199997,145.320007,146.740005,22378400,0.0,0.0
2023-11-27 00:00:00-05:00,147.529999,149.259995,146.880005,147.729996,53762400,0.0,0.0
2023-11-28 00:00:00-05:00,146.979996,147.600006,145.529999,147.029999,42711700,0.0,0.0
2023-11-29 00:00:00-05:00,147.850006,148.539993,145.970001,146.320007,40610900,0.0,0.0
2023-11-30 00:00:00-05:00,144.759995,146.929993,144.330002,146.089996,65814000,0.0,0.0
2023-12-01 00:00:00-05:00,146.000000,147.250000,145.550003,147.029999,39924600,0.0,0.0
2023-12-04 00:00:00-05:00,145.250000,145.350006,142.809998,144.839996,48294200,0.0,0.0
2023-12-05 00:00:00-05:00,143.550003,148.570007,143.130005,146.880005,46822400,0.0,0.0
2023-12-06 00:00:00-05:00,147.580002,147.850006,144.279999,144.520004,39679000,0.0,0.0
2023-12-07 00:00:00-05:00,146.149994,147.919998,145.339996,146.880005,52352800,0.0,0.0
2023-12-08 00:00:00-05:00,145.479996,147.839996,145.399994,147.419998,41858000,0.0,0.0
2023-12-11 00:00:00-05:00,145.660004,146.190002,143.639999,145.889999,50907300,0.0,0.0
2023-12-12 00:00:00-05:00,145.520004,147.500000,145.300003,147.479996,44944300,0.0,0.0
2023-12-13 00:00:00-05:00,148.119995,149.460007,146.820007,148.839996,52766200,0.0,0.0
2023-12-14 00:00:00-05:00,149.929993,150.539993,145.520004,147.419998,58400800,0.0,0.0
2023-12-15 00:00:00-05:00,148.380005,150.570007,147.880005,149.970001,110039100,0.0,0.0
2023-12-18 00:00:00-05:00,150.559998,154.850006,150.050003,154.070007,62512800,0.0,0.0
2023-12-19 00:00:00-05:00,154.399994,155.119995,152.690002,153.789993,43171300,0.0,0.0
2023-12-20 00:00:00-05:00,152.899994,155.630005,151.559998,152.119995,50322100,0.0,0.0
2023-12-21 00:00:00-05:00,153.300003,153.970001,152.100006,153.839996,36305700,0.0,0.0
2023-12-22 00:00:00-05:00,153.770004,154.350006,152.710007,153.419998,29480100,0.0,0.0
2023-12-26 00:00:00-05:00,153.559998,153.979996,153.029999,153.410004,25067200,0.0,0.0
2023-12-27 00:00:00-05:00,153.559998,154.779999,153.119995,153.339996,31434700,0.0,0.0
2023-12-28 00:00:00-05:00,153.720001,154.080002,152.949997,153.380005,27057000,0.0,0.0
2023-12-29 00:00:00-05:00,153.100006,153.889999,151.029999,151.940002,39789000,0.0,0.0
2024-01-02 00:00:00-05:00,151.539993,152.380005,148.389999,149.929993,47339400,0.0,0.0
2024-01-03 00:00:00-05:00,149.199997,151.050003,148.330002,148.470001,49425500,0.0,0.0
2024-01-04 00:00:00-05:00,145.589996,147.380005,144.050003,144.570007,56039800,0.0,0.0
2024-01-05 00:00:00-05:00,144.690002,146.589996,144.529999,145.240005,45124800,0.0,0.0
2024-01-08 00:00:00-05:00,146.740005,149.399994,146.149994,149.100006,46757100,0.0,0.0
2024-01-09 00:00:00-05:00,148.330002,151.710007,148.210007,151.369995,43812600,0.0,0.0
2024-01-10 00:00:00-05:00,152.059998,154.419998,151.880005,153.729996,44421800,0.0,0.0
2024-01-11 00:00:00-05:00,155.039993,157.169998,153.119995,155.179993,49072700,0.0,0.0
2024-01-12 00:00:00-05:00,155.389999,156.199997,154.009995,154.619995,40460300,0.0,0.0
2024-01-16 00:00:00-05:00,153.529999,154.990005,152.149994,153.160004,41384600,0.0,0.0
2024-01-17 00:00:00-05:00,151.490005,152.149994,149.910004,151.710007,34953400,0.0,0.0
2024-01-18 00:00:00-05:00,152.770004,153.779999,151.820007,153.500000,37850200,0.0,0.0
2024-01-19 00:00:00-05:00,153.830002,155.759995,152.740005,155.339996,51033700,0.0,0.0
2024-01-22 00:00:00-05:00,156.889999,157.050003,153.899994,154.779999,43687500,0.0,0.0
2024-01-23 00:00:00-05:00,154.850006,156.210007,153.929993,156.020004,37986000,0.0,0.0
2024-01-24 00:00:00-05:00,157.800003,158.509995,156.479996,156.869995,48547300,0.0,0.0
2024-01-25 00:00:00-05:00,156.949997,158.509995,154.550003,157.750000,43638600,0.0,0.0
2024-01-26 00:00:00-05:00,158.419998,160.720001,157.910004,159.119995,51047400,0.0,0.0
2024-01-29 00:00:00-05:00,159.339996,161.289993,158.899994,161.259995,45270400,0.0,0.0
2024-01-30 00:00:00-05:00,160.699997,161.729996,158.490005,159.000000,45207400,0.0,0.0
2024-01-31 00:00:00-05:00,157.000000,159.009995,154.809998,155.199997,50284400,0.0,0.0
2024-02-01 00:00:00-05:00,155.869995,159.759995,155.619995,159.279999,76542400,0.0,0.0
2024-02-02 00:00:00-05:00,169.190002,172.500000,167.330002,171.809998,117154900,0.0,0.0
2024-02-05 00:00:00-05:00,170.199997,170.550003,167.699997,170.309998,55081300,0.0,0.0
2024-02-06 00:00:00-05:00,169.389999,170.710007,167.649994,169.149994,42505500,0.0,0.0
2024-02-07 00:00:00-05:00,169.479996,170.880005,168.940002,170.529999,47174100,0.0,0.0
2024-02-08 00:00:00-05:00,169.649994,171.429993,168.880005,169.839996,42316500,0.0,0.0

In [5]:
df_AMZN.index = pd.to_datetime(df_AMZN.index)

In [22]:
weekly_df = df_AMZN.resample('W').first()
weekly_df.index = df_AMZN.groupby(df_AMZN.index.to_period('W')).apply(lambda x: x.index.min()).values

C:\Users\mattp\AppData\Local\Temp\ipykernel_24056\3560551579.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  weekly_df.index = df_AMZN.groupby(df_AMZN.index.to_period('W')).apply(lambda x: x.index.min()).values

In [23]:
display(weekly_df)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
1997-05-15 04:00:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1997-05-19 04:00:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0
1997-05-27 04:00:00,0.075521,0.082292,0.072917,0.079167,173952000,0.0,0.0
1997-06-02 04:00:00,0.075521,0.076563,0.075000,0.075521,11832000,0.0,0.0
1997-06-09 04:00:00,0.082813,0.085417,0.082813,0.084375,47040000,0.0,0.0
...,...,...,...,...,...,...,...
2024-01-08 05:00:00,146.740005,149.399994,146.149994,149.100006,46757100,0.0,0.0
2024-01-16 05:00:00,153.529999,154.990005,152.149994,153.160004,41384600,0.0,0.0
2024-01-22 05:00:00,156.889999,157.050003,153.899994,154.779999,43687500,0.0,0.0
2024-01-29 05:00:00,159.339996,161.289993,158.899994,161.259995,45270400,0.0,0.0
2024-02-05 05:00:00,170.199997,170.550003,167.699997,170.309998,55081300,0.0,0.0

In [25]:
monthly_df = df_AMZN.resample('M').first()
monthly_df.index = df_AMZN.groupby(df_AMZN.index.to_period('M')).apply(lambda x: x.index.min()).values

C:\Users\mattp\AppData\Local\Temp\ipykernel_24056\812631320.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  monthly_df.index = df_AMZN.groupby(df_AMZN.index.to_period('M')).apply(lambda x: x.index.min()).values

In [26]:
display(monthly_df)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
1997-05-15 04:00:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1997-06-02 04:00:00,0.075521,0.076563,0.075000,0.075521,11832000,0.0,0.0
1997-07-01 04:00:00,0.077083,0.077083,0.075521,0.075781,25848000,0.0,0.0
1997-08-01 04:00:00,0.117188,0.120833,0.112500,0.120833,71760000,0.0,0.0
1997-09-02 04:00:00,0.117188,0.118750,0.116667,0.117708,14640000,0.0,0.0
...,...,...,...,...,...,...,...
2023-10-02 04:00:00,127.279999,130.470001,126.540001,129.460007,48029700,0.0,0.0
2023-11-01 04:00:00,133.960007,137.350006,133.710007,137.000000,61529400,0.0,0.0
2023-12-01 05:00:00,146.000000,147.250000,145.550003,147.029999,39924600,0.0,0.0
2024-01-02 05:00:00,151.539993,152.380005,148.389999,149.929993,47339400,0.0,0.0
2024-02-01 05:00:00,155.869995,159.759995,155.619995,159.279999,76542400,0.0,0.0

In [36]:
weekly_returns = (weekly_df["Close"].pct_change()).dropna()
monthly = (monthly_df["Close"].pct_change()).dropna()

In [38]:
display(weekly_returns)
display(monthly)

1997-05-19 04:00:00   -0.127659
1997-05-27 04:00:00   -0.073170
1997-06-02 04:00:00   -0.046055
1997-06-09 04:00:00    0.117239
1997-06-16 04:00:00   -0.067899
                         ...
2024-01-08 05:00:00   -0.005536
2024-01-16 05:00:00    0.027230
2024-01-22 05:00:00    0.010577
2024-01-29 05:00:00    0.041866
2024-02-05 05:00:00    0.056121
Name: Close, Length: 1395, dtype: float64

1997-06-02 04:00:00   -0.228724
1997-07-01 04:00:00    0.003443
1997-08-01 04:00:00    0.594503
1997-09-02 04:00:00   -0.025862
1997-10-01 04:00:00    0.707972
                         ...
2023-10-02 04:00:00   -0.062699
2023-11-01 04:00:00    0.058242
2023-12-01 05:00:00    0.073212
2024-01-02 05:00:00    0.019724
2024-02-01 05:00:00    0.062362
Name: Close, Length: 321, dtype: float64

In [44]:
display(df_AMZN[-60:-1])

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-11-14 00:00:00-05:00,145.000000,147.259995,144.679993,145.800003,56674600,0.0,0.0
2023-11-15 00:00:00-05:00,147.059998,147.289993,142.589996,143.199997,63875700,0.0,0.0
2023-11-16 00:00:00-05:00,140.910004,143.320007,139.520004,142.830002,49653500,0.0,0.0
2023-11-17 00:00:00-05:00,142.660004,145.229996,142.539993,145.179993,49636700,0.0,0.0
2023-11-20 00:00:00-05:00,145.130005,146.630005,144.729996,146.130005,41951200,0.0,0.0
2023-11-21 00:00:00-05:00,143.910004,144.050003,141.500000,143.899994,71226000,0.0,0.0
2023-11-22 00:00:00-05:00,144.570007,147.740005,144.570007,146.710007,45669100,0.0,0.0
2023-11-24 00:00:00-05:00,146.699997,147.199997,145.320007,146.740005,22378400,0.0,0.0
2023-11-27 00:00:00-05:00,147.529999,149.259995,146.880005,147.729996,53762400,0.0,0.0
2023-11-28 00:00:00-05:00,146.979996,147.600006,145.529999,147.029999,42711700,0.0,0.0
2023-11-29 00:00:00-05:00,147.850006,148.539993,145.970001,146.320007,40610900,0.0,0.0
2023-11-30 00:00:00-05:00,144.759995,146.929993,144.330002,146.089996,65814000,0.0,0.0
2023-12-01 00:00:00-05:00,146.000000,147.250000,145.550003,147.029999,39924600,0.0,0.0
2023-12-04 00:00:00-05:00,145.250000,145.350006,142.809998,144.839996,48294200,0.0,0.0
2023-12-05 00:00:00-05:00,143.550003,148.570007,143.130005,146.880005,46822400,0.0,0.0
2023-12-06 00:00:00-05:00,147.580002,147.850006,144.279999,144.520004,39679000,0.0,0.0
2023-12-07 00:00:00-05:00,146.149994,147.919998,145.339996,146.880005,52352800,0.0,0.0
2023-12-08 00:00:00-05:00,145.479996,147.839996,145.399994,147.419998,41858000,0.0,0.0
2023-12-11 00:00:00-05:00,145.660004,146.190002,143.639999,145.889999,50907300,0.0,0.0
2023-12-12 00:00:00-05:00,145.520004,147.500000,145.300003,147.479996,44944300,0.0,0.0
2023-12-13 00:00:00-05:00,148.119995,149.460007,146.820007,148.839996,52766200,0.0,0.0
2023-12-14 00:00:00-05:00,149.929993,150.539993,145.520004,147.419998,58400800,0.0,0.0
2023-12-15 00:00:00-05:00,148.380005,150.570007,147.880005,149.970001,110039100,0.0,0.0
2023-12-18 00:00:00-05:00,150.559998,154.850006,150.050003,154.070007,62512800,0.0,0.0
2023-12-19 00:00:00-05:00,154.399994,155.119995,152.690002,153.789993,43171300,0.0,0.0
2023-12-20 00:00:00-05:00,152.899994,155.630005,151.559998,152.119995,50322100,0.0,0.0
2023-12-21 00:00:00-05:00,153.300003,153.970001,152.100006,153.839996,36305700,0.0,0.0
2023-12-22 00:00:00-05:00,153.770004,154.350006,152.710007,153.419998,29480100,0.0,0.0
2023-12-26 00:00:00-05:00,153.559998,153.979996,153.029999,153.410004,25067200,0.0,0.0
2023-12-27 00:00:00-05:00,153.559998,154.779999,153.119995,153.339996,31434700,0.0,0.0
2023-12-28 00:00:00-05:00,153.720001,154.080002,152.949997,153.380005,27057000,0.0,0.0
2023-12-29 00:00:00-05:00,153.100006,153.889999,151.029999,151.940002,39789000,0.0,0.0
2024-01-02 00:00:00-05:00,151.539993,152.380005,148.389999,149.929993,47339400,0.0,0.0
2024-01-03 00:00:00-05:00,149.199997,151.050003,148.330002,148.470001,49425500,0.0,0.0
2024-01-04 00:00:00-05:00,145.589996,147.380005,144.050003,144.570007,56039800,0.0,0.0
2024-01-05 00:00:00-05:00,144.690002,146.589996,144.529999,145.240005,45124800,0.0,0.0
2024-01-08 00:00:00-05:00,146.740005,149.399994,146.149994,149.100006,46757100,0.0,0.0
2024-01-09 00:00:00-05:00,148.330002,151.710007,148.210007,151.369995,43812600,0.0,0.0
2024-01-10 00:00:00-05:00,152.059998,154.419998,151.880005,153.729996,44421800,0.0,0.0
2024-01-11 00:00:00-05:00,155.039993,157.169998,153.119995,155.179993,49072700,0.0,0.0
2024-01-12 00:00:00-05:00,155.389999,156.199997,154.009995,154.619995,40460300,0.0,0.0
2024-01-16 00:00:00-05:00,153.529999,154.990005,152.149994,153.160004,41384600,0.0,0.0
2024-01-17 00:00:00-05:00,151.490005,152.149994,149.910004,151.710007,34953400,0.0,0.0
2024-01-18 00:00:00-05:00,152.770004,153.779999,151.820007,153.500000,37850200,0.0,0.0
2024-01-19 00:00:00-05:00,153.830002,155.759995,152.740005,155.339996,51033700,0.0,0.0
2024-01-22 00:00:00-05:00,156.889999,157.050003,153.899994,154.779999,43687500,0.0,0.0
2024-01-23 00:00:00-05:00,154.850006,156.210007,153.929993,156.020004,37986000,0.0,0.0
2024-01-24 00:00:00-05:00,157.800003,158.509995,156.479996,156.869995,48547300,0.0,0.0
2024-01-25 00:00:00-05:00,156.949997,158.509995,154.550003,157.750000,43638600,0.0,0.0
2024-01-26 00:00:00-05:00,158.419998,160.720001,157.910004,159.119995,51047400,0.0,0.0
2024-01-29 00:00:00-05:00,159.339996,161.289993,158.899994,161.259995,45270400,0.0,0.0
2024-01-30 00:00:00-05:00,160.699997,161.729996,158.490005,159.000000,45207400,0.0,0.0
2024-01-31 00:00:00-05:00,157.000000,159.009995,154.809998,155.199997,50284400,0.0,0.0
2024-02-01 00:00:00-05:00,155.869995,159.759995,155.619995,159.279999,76542400,0.0,0.0
2024-02-02 00:00:00-05:00,169.190002,172.500000,167.330002,171.809998,117154900,0.0,0.0
2024-02-05 00:00:00-05:00,170.199997,170.550003,167.699997,170.309998,55081300,0.0,0.0
2024-02-06 00:00:00-05:00,169.389999,170.710007,167.649994,169.149994,42505500,0.0,0.0
2024-02-07 00:00:00-05:00,169.479996,170.880005,168.940002,170.529999,47174100,0.0,0.0
2024-02-08 00:00:00-05:00,169.649994,171.429993,168.880005,169.839996,42316500,0.0,0.0

In [48]:
year_df_AMZ = df_AMZN.resample('Y').first()
year_df_AMZ.index = df_AMZN.groupby(df_AMZN.index.to_period('Y')).apply(lambda x: x.index.min()).values

C:\Users\mattp\AppData\Local\Temp\ipykernel_24056\729121823.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  year_df_AMZ.index = df_AMZN.groupby(df_AMZN.index.to_period('Y')).apply(lambda x: x.index.min()).values

In [50]:
YTD_returns = (df_AMZN["Close"].iloc[-1] - year_df_AMZ['Close'].iloc[-1]) / year_df_AMZ['Close'].iloc[-1]

In [51]:
display(YTD_returns)

0.16354302321273803